SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER SCHEMA `judbrass` DEFAULT CHARACTER SET utf8  DEFAULT COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS `judbrass`.`users` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(300) NULL DEFAULT NULL,
    `email` VARCHAR(300) NULL DEFAULT NULL,
    `password` VARCHAR(300) NULL DEFAULT NULL,
    `criado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `modificado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `ultimo_acesso` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `perfil` JSON NULL,
    `status` TINYINT(1) NULL DEFAULT NULL,
    `alterar_senha` VARCHAR(5) NULL DEFAULT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8
    ROW_FORMAT = DEFAULT;

CREATE TABLE IF NOT EXISTS `judbrass`.`servicos` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `servico` VARCHAR(191) NULL DEFAULT NULL,
    `acao` VARCHAR(191) NULL DEFAULT NULL,
    `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `judbrass`.`perfil` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `descricao` VARCHAR(191) NULL DEFAULT NULL,
    `servicos` JSON NULL,
    `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
